name: Main PR Workflow

on:
  push:
    branches:
      [ main ]

jobs:
  build:
    name: Java-Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Connect to PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'cjoshi'
          postgresql user: 'cjoshi'
          postgresql password: 'cjoshi'
      - name: Build with Maven
        working-directory: Assignment3
        run: mvn clean install
      - name: Running test cases
        working-directory: Assignment3
        run: mvn test -Dtest=IntegrationTest
